name: Tests
on:
  pull_request:
  push:
    branches: [main]
    
jobs:

  unit-tests:
    name: Unit Tests
    needs: dependencies
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Running Unit Tests
        run: make test

      - name: Running Integration Tests
        run: make itest
